networks:
  party-network:
    driver: bridge

volumes:
  postgres-data:

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
        # Ensure that the variables in .env match the same variables in devcontainer.json
        - .env
    volumes:
      - ../..:/workspaces:cached
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity
    networks:
      - party-network
    depends_on:
      - db
      - pregame
      - bouncer

  pregame:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
        - .env
    volumes:
      - ../..:/workspaces:cached
    working_dir: /workspaces/party/pregame
    command: bash -c "cargo build && ./target/debug/pregame"
    ports:
      - "50051:50051"
    depends_on:
      - db
    networks:
      - party-network

  bouncer:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
        - .env
    volumes:
      - ../..:/workspaces:cached
    working_dir: /workspaces/party/bouncer
    command: bash -c "npm install && npm run dev"
    ports:
      - "3000:3000"
    depends_on:
      - pregame
    networks:
      - party-network
    environment:
      - NODE_ENV=development
      - GRPC_SERVER_URL=pregame:50051

  db:
    image: postgres:14.1
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql:ro
    ports:
      - "5432:5432"
    networks:
      - party-network
    env_file:
        # Ensure that the variables in .env match the same variables in devcontainer.json
        - .env